[package]
name = "pdbman"
version = "0.5.3"
authors = ["Benedikt M. Flöser <benedikt.floeser@cec.mpg.de>"]
edition = "2018"
description = "Analyzes and edits PDB files for usage in QM/MM calculations with the ORCA Quantum Chemistry package"
license = "GPL-2.0-or-later"

[dependencies]
prettytable-rs = "0.8"
clap = "3.0.0-beta.2"
strum = "0.20.0"
strum_macros = "0.20.1"
regex = "^1.4"
lazy_static = "*"
itertools = "*"
rayon = "^1.5"
#pdbtbx = {version = "^0.7", features = ["rayon", "rstar"]}
pdbtbx = {git = "https://github.com/DocKDE/pdbtbx", branch = "parser_check", features = ["rayon", "rstar"]}
