[package]
name = "pdbman"
version = "0.3.0"
authors = ["Benedikt M. Flöser <benedikt.floeser@cec.mpg.de>"]
edition = "2018"
description = "Parses and edits PDB files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8"
clap = "3.0.0-beta.2"
strum = "0.20.0"
strum_macros = "0.20.1"
rstar = "0.8.2"
pdbtbx = "^0.6.2"
#pdbtbx = {path = "/home/floeserb/Nextcloud/Code/rust/pdbtbx"}