[package]
name = "pdbman"
version = "0.3.3"
authors = ["Benedikt M. Flöser <benedikt.floeser@cec.mpg.de>"]
edition = "2018"
description = "Analyzes and edits PDB files for usage in QM/MM calculations with the ORCA Quantum Chemistry package"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8"
clap = "3.0.0-beta.2"
strum = "0.20.0"
strum_macros = "0.20.1"
#anyhow = "^1.0"
rstar = "0.8.2"
#pdbtbx = "^0.6.2"
regex = "^1.4"
itertools = "*"
pdbtbx = {path = "/home/floeserb/Nextcloud/Code/rust/pdbtbx"}