# Stable features
newline_style = "Native"
edition = "2021"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true

# nightly
# fn_single_line = true
# format_strings = true
# imports_granularity = "Crate"
# match_block_trailing_comma = true
# reorder_impl_items = true
# group_imports = "StdExternalCrate"