use clap::{Arg, ArgGroup, Command};

/// Defines all Args, their configuration and all ArgGroups as defined by clap.
pub fn clap_args() -> Command<'static> {
    Command::new("")
        // .setting(CommandSettings::ArgRequiredElseHelp)
        // .setting(CommandSettings::SubcommandRequiredElseHelp)
        // .setting(CommandSettings::VersionlessSubcommands)
        // .setting(CommandSettings::InferSubcommands)
        .infer_subcommands(true)
        .no_binary_name(true)
        // .setting(CommandSettings::NoBinaryName)
        // .setting(CommandSettings::NoAutoHelp)
        .subcommand(Command::new("Query")
            .about("Query for atoms and residues")
            .visible_aliases(&["query"])
            .arg(Arg::new("Input")
                .help("Input for atom selection")
                .required(true)
                .multiple_values(true))
        )
        .subcommand(Command::new("Analyze")
            .about("Analysis QM and active regions")
            .visible_aliases(&["analyze", "Y", "y"])
            .arg(
                Arg::new("Residues")
                    .help("Residue Mode")
                    .long("residues")
                    .short('r')
            )
            .arg(
                Arg::new("Atoms")
                    .help("Atom Mode")
                    .long("atoms")
                    .short('t')
            )
            .arg(
                Arg::new("QM1")
                    .help("QM1 region")
                    .long("qm1")
                    .short('q')
            )
            .arg(
                Arg::new("QM2")
                    .help("QM2 region")
                    .long("qm2")
                    .short('o')
            )
            .arg(
                Arg::new("Active")
                    .help("Active region")
                    .long("active")
                    .short('a')
            )
            .arg(
                Arg::new("Clashes")
                    .help("Find LJ clashes")
                    .long("clashes")
                    .short('c')
            )
            .arg(
                Arg::new("Contacts")
                    .help("Find vdW contacts")
                    .long("contacts")
                    .short('n')
            )
            .group(ArgGroup::new("target").args(&["Residues", "Atoms"]).requires("region"))
            .group(ArgGroup::new("region").args(&["QM1", "QM2", "Active"]).requires("target"))
            .group(ArgGroup::new("distances").args(&["Clashes", "Contacts"]))
        )
        .subcommand(Command::new("Add")
            .about("Add atoms or residues to QM or active regions")
            .visible_aliases(&["add", "A", "a"])
            .arg(Arg::new("Input")
                .help("Input for atom selection")
                .required(true)
                .multiple_values(true))
            .arg(
                Arg::new("QM1")
                    .help("QM1 region")
                    .long("qm1")
                    .short('q')
            )
            .arg(
                Arg::new("QM2")
                    .help("QM2 region")
                    .long("qm2")
                    .short('o')
            )
            .arg(
                Arg::new("Active")
                    .help("Active region")
                    .long("active")
                    .short('a')
            )
            .arg(
                Arg::new("Sidechain")
                    .help("Use only sidechains of protein")
                    .long("sidechain")
                    .short('d')
            )
            .arg(
                Arg::new("Backbone")
                    .help("Use only backbones of protein")
                    .long("backbone")
                    .short('b')
            )
            .group(
                ArgGroup::new("partial")
                    .args(&["Sidechain", "Backbone"])
                    .requires_all(&["region", "source"]),
            )
            .group(
                ArgGroup::new("region")
                    .args(&["QM1", "QM2", "Active"])
                    .required(true))
        )
        .subcommand(Command::new("Remove")
            .about("Remove atoms or residues to QM or active regions")
            .visible_aliases(&["remove"])
            .arg(Arg::new("Input")
                .help("Input for atom selection")
                // .required(true)
                .multiple_values(true))
            .arg(
                Arg::new("QM1")
                    .help("QM1 region")
                    .long("qm1")
                    .short('q')
            )
            .arg(
                Arg::new("QM2")
                    .help("QM2 region")
                    .long("qm2")
                    .short('o')
            )
            .arg(
                Arg::new("Active")
                    .help("Active region")
                    .long("active")
                    .short('a')
            )
            .arg(
                Arg::new("Sidechain")
                    .help("Use only sidechains of protein")
                    .long("sidechain")
                    .short('d')
            )
            .arg(
                Arg::new("Backbone")
                    .help("Use only backbones of protein")
                    .long("backbone")
                    .short('b')
            )
            .group(
                ArgGroup::new("partial")
                    .args(&["Sidechain", "Backbone"])
                    .requires_all(&["region", "source"]),
            )
            .group(
                ArgGroup::new("region")
                    .args(&["QM1", "QM2", "Active"])
                )
        )
        .subcommand(Command::new("Write")
            .about("Write PDB information")
            .visible_aliases(&["write"])
            .arg(
                Arg::new("State")
                    .help("Write state of system")
                    .long("state")
                    .short('s')
            )
            .arg(
                Arg::new("Outfile")
                    .help("File path for writing output")
                    .long("file")
                    .short('f')
                    .takes_value(true),
            )
            .arg(
                Arg::new("Overwrite")
                    .help("Overwrite PDB input file")
                    .long("overwrite")
                    .short('w')
                    .conflicts_with_all(&["QM1", "QM2", "Active", "Atoms", "Residues"])
            )
            .group(
                ArgGroup::new("output")
                    .args(&["Outfile", "Overwrite"])
            )
        )
        .subcommand(Command::new("Measure")
            .about("Measure distances and angles")
            .visible_aliases(&["measure"])
            .arg(Arg::new("Atoms")
                 .help("Atom IDs to be measured")
                 .long("atoms")
                 .short('a')
                 .takes_value(true)
                 .multiple_values(true)
                 .min_values(2)
                 .max_values(4)
                 )
            .arg(Arg::new("Sphere")
                 .help("Sphere around which to be measured")
                 .long("sphere")
                 .short('s')
                 .takes_value(true)
                 .multiple_values(true)
                 .number_of_values(2)
                 )
            .group(
                ArgGroup::new("measuretarget")
                    .args(&["Atoms", "Sphere"])
                    .required(true)
                )
            )
}
